/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import doan_oracle.DBconnection;
import doan_oracle.frm_DangNhap;
import GUI.ImageHelper;


/**
 *
 * @author ADMIN
 */
public class Dialog_MTT_SearchSanPham extends javax.swing.JDialog {
    PreparedStatement preparedStatement = null;
    ResultSet resultset = null;
    Connection connection = null;
    BufferedImage bufImg = null;
    /**
     * Creates new form Dialog_MTT_SearchSanPham
     */
    public Dialog_MTT_SearchSanPham(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        showData();
    }
    
    public static String maSP = "";
    public static String tenSP;
    public static String soLuong;
    public static String giamGia;
    public static String donGia;
    public static String thanhTien;
    
    
    public void showData(){
        try {
            // TODO add your handling code here:
            connection = DBconnection.getConnection(frm_DangNhap.tenDangNhap(), frm_DangNhap.matKhauDangNhap());
            String query = "SELECT * FROM tbl_SanPham ";
            preparedStatement = connection.prepareStatement(query);
            resultset = preparedStatement.executeQuery();
            tbLDanhSachTimKiem.removeAll();
            String[] arr = {"Mã SP", "Tên SP", "Loại SP", "Giá bán", "Giảm giá", "Xuất xứ"};
            DefaultTableModel model = new DefaultTableModel(arr, 0);
            
            while(resultset.next()){
                Vector vector = new Vector();
                vector.add(resultset.getString("PK_iSanPhamID"));
                vector.add(resultset.getString("sTenSanPham"));
                vector.add(resultset.getString("FK_sDanhMucSanPhamID"));
                vector.add(resultset.getString("fGiaBan"));
                vector.add(resultset.getString("FK_iGiamGiaID"));
                vector.add(resultset.getString("sXuatXu"));
                
                model.addRow(vector);
            }
            tbLDanhSachTimKiem.setModel(model);
        } catch (SQLException ex) {
            //Logger.getLogger(Dialog_MTT_SearchSanPham.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Erro");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTenSP = new javax.swing.JTextField();
        btnSearchTenSP = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        btnThemSPVaoHoaDon = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLDanhSachTimKiem = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icon/timkiem-25.png"))); // NOI18N

        txtTenSP.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N

        btnSearchTenSP.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        btnSearchTenSP.setText("Tìm kiếm");
        btnSearchTenSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchTenSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearchTenSP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearchTenSP))
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mô tả sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 17), new java.awt.Color(255, 51, 51))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel2.setText("Mô tả: ");

        txtMoTa.setColumns(10);
        txtMoTa.setFont(new java.awt.Font("Monospaced", 0, 17)); // NOI18N
        txtMoTa.setEditable(false);
        txtMoTa.setRows(1);
        txtMoTa.setTabSize(5);
        jScrollPane2.setViewportView(txtMoTa);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel3.setText("Hình ảnh: ");

        image.setBackground(new java.awt.Color(255, 255, 255));
        image.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        image.setText("No Image");

        btnThemSPVaoHoaDon.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        btnThemSPVaoHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icon/them-25.png"))); // NOI18N
        btnThemSPVaoHoaDon.setText("Thêm vào hóa đơn");
        btnThemSPVaoHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSPVaoHoaDonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel4.setText("Số lượng: ");

        txtSoLuong.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtSoLuong.setText("1");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Thoát");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(btnThemSPVaoHoaDon)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemSPVaoHoaDon)
                    .addComponent(jButton1))
                .addGap(25, 25, 25))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 17), new java.awt.Color(255, 51, 0))); // NOI18N

        tbLDanhSachTimKiem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbLDanhSachTimKiem.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        tbLDanhSachTimKiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên SP", "Giá bán", "Giảm giá", "Xuất xứ", "Loại SP"
            }
        ));
        tbLDanhSachTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbLDanhSachTimKiemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbLDanhSachTimKiem);
        if (tbLDanhSachTimKiem.getColumnModel().getColumnCount() > 0) {
            tbLDanhSachTimKiem.getColumnModel().getColumn(0).setPreferredWidth(30);
            tbLDanhSachTimKiem.getColumnModel().getColumn(1).setPreferredWidth(80);
            tbLDanhSachTimKiem.getColumnModel().getColumn(2).setPreferredWidth(40);
            tbLDanhSachTimKiem.getColumnModel().getColumn(3).setPreferredWidth(40);
            tbLDanhSachTimKiem.getColumnModel().getColumn(4).setPreferredWidth(40);
            tbLDanhSachTimKiem.getColumnModel().getColumn(5).setPreferredWidth(40);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btnSearchTenSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchTenSPActionPerformed
        try {
            // TODO add your handling code here:
            connection = DBconnection.getConnection(frm_DangNhap.tenDangNhap(), frm_DangNhap.matKhauDangNhap());
            String query = "SELECT * FROM tbl_SanPham WHERE sTenSanPham LIKE '%"+txtTenSP.getText()+"%'";
            preparedStatement = connection.prepareStatement(query);
            resultset = preparedStatement.executeQuery();
            tbLDanhSachTimKiem.removeAll();
            String[] arr = {"Mã SP", "Tên SP", "Loại SP", "Giá bán", "Giảm giá", "Xuất xứ"};
            DefaultTableModel model = new DefaultTableModel(arr, 0);
            
            while(resultset.next()){
                Vector vector = new Vector();
                vector.add(resultset.getString("PK_iSanPhamID"));
                vector.add(resultset.getString("sTenSanPham"));
                vector.add(resultset.getString("FK_sDanhMucSanPhamID"));
                vector.add(resultset.getString("fGiaBan"));
                vector.add(resultset.getString("FK_iGiamGiaID"));
                vector.add(resultset.getString("sXuatXu"));
                
                model.addRow(vector);
            }
            tbLDanhSachTimKiem.setModel(model);
        } catch (SQLException ex) {
            //Logger.getLogger(Dialog_MTT_SearchSanPham.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Erro");
        }
    }//GEN-LAST:event_btnSearchTenSPActionPerformed
    
    
    private void tbLDanhSachTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLDanhSachTimKiemMouseClicked
        try {
            // TODO add your handling code here:
            int i = tbLDanhSachTimKiem.getSelectedRow();
          
            TableModel model = tbLDanhSachTimKiem.getModel();
                
            
            
            
            txtMoTa.setText(model.getValueAt(i, 0).toString());
            String query = "SELECT * FROM tbl_SanPham WHERE PK_iSanPhamID = '"+txtMoTa.getText()+"'";
            connection = DBconnection.getConnection(frm_DangNhap.tenDangNhap(), frm_DangNhap.matKhauDangNhap());
            preparedStatement = connection.prepareStatement(query);
            resultset = preparedStatement.executeQuery();
            
            if(resultset.next()){
                txtMoTa.setText(resultset.getString("sMoTa"));
                String data = resultset.getString("sImage");
               
                    maSP = resultset.getString("PK_iSanPhamID");
                    tenSP = resultset.getString("sTenSanPham");
                    soLuong = txtSoLuong.getText();
                    donGia = resultset.getString("fGiaBan");
                    giamGia = "1";
                   // byte[] in = resultset.getBytes("sImage");
                    //image.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().createImage(in)));
                    //Image img = ImageHelper.createImageFromByteArray(resultset.getString("sImage"), "jpg");
                    //image.setIcon(new ImageIcon(img));
                    
            }
            
            
            
            
        } catch (SQLException ex) {           
            JOptionPane.showMessageDialog(this, "Chưa chọn sản phẩm nào");
        }
    }//GEN-LAST:event_tbLDanhSachTimKiemMouseClicked

    private void btnThemSPVaoHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSPVaoHoaDonActionPerformed
        //if(maSP == ""){
            //JOptionPane.showMessageDialog(this, "Chưa chọn sản phẩm nào2");
        //maSP = null;
        dispose();
        //}
        //this.setVisible(false);
    }//GEN-LAST:event_btnThemSPVaoHoaDonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    public String getTextF(){
        return maSP;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dialog_MTT_SearchSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dialog_MTT_SearchSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dialog_MTT_SearchSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dialog_MTT_SearchSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dialog_MTT_SearchSanPham dialog = new Dialog_MTT_SearchSanPham(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearchTenSP;
    private javax.swing.JButton btnThemSPVaoHoaDon;
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbLDanhSachTimKiem;
    private javax.swing.JTextArea txtMoTa;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenSP;
    // End of variables declaration//GEN-END:variables
}
