/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author ADMIN
 */
public class frm_Chinh extends javax.swing.JFrame {

    /**
     * Creates new form frm_Chinh
     */
    public frm_Chinh() {
        initComponents();
        //pnChild.setSize(2500, 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnChinh = new javax.swing.JPanel();
        lbHome = new javax.swing.JLabel();
        pnChucNang = new javax.swing.JPanel();
        btnQLSanPham = new javax.swing.JButton();
        btnQLNhanVien = new javax.swing.JButton();
        btnDonDatHang = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        btnCaiDat = new javax.swing.JButton();
        pnThanhDonw = new javax.swing.JPanel();
        tab = new javax.swing.JTabbedPane();
        mnuBar = new javax.swing.JMenuBar();
        mnuTaiKhoan = new javax.swing.JMenu();
        mnuDangXuat = new javax.swing.JMenuItem();
        mnuDoiMatKhau = new javax.swing.JMenuItem();
        mnuQLChinh = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        mnuQLNhanVien = new javax.swing.JMenu();
        mnuThongKe = new javax.swing.JMenu();
        mnuCaiDat = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnChinh.setPreferredSize(new java.awt.Dimension(1654, 300));

        lbHome.setBackground(new java.awt.Color(255, 153, 153));

        pnChucNang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnQLSanPham.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnQLSanPham.setText("Quản lí sản phẩm");
        btnQLSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLSanPhamActionPerformed(evt);
            }
        });

        btnQLNhanVien.setText("Quản lí nhân viên");
        btnQLNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLNhanVienActionPerformed(evt);
            }
        });

        btnDonDatHang.setText("Đơn đặt hàng");

        btnThongKe.setText("Thống kê");

        btnCaiDat.setText("Cài đặt");

        javax.swing.GroupLayout pnChucNangLayout = new javax.swing.GroupLayout(pnChucNang);
        pnChucNang.setLayout(pnChucNangLayout);
        pnChucNangLayout.setHorizontalGroup(
            pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnQLSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
            .addComponent(btnQLNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDonDatHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCaiDat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnChucNangLayout.setVerticalGroup(
            pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChucNangLayout.createSequentialGroup()
                .addComponent(btnQLSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnQLNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDonDatHang, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCaiDat, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addGap(42, 42, 42))
        );

        pnThanhDonw.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnThanhDonwLayout = new javax.swing.GroupLayout(pnThanhDonw);
        pnThanhDonw.setLayout(pnThanhDonwLayout);
        pnThanhDonwLayout.setHorizontalGroup(
            pnThanhDonwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );
        pnThanhDonwLayout.setVerticalGroup(
            pnThanhDonwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnChinhLayout = new javax.swing.GroupLayout(pnChinh);
        pnChinh.setLayout(pnChinhLayout);
        pnChinhLayout.setHorizontalGroup(
            pnChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChinhLayout.createSequentialGroup()
                .addGroup(pnChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnChucNang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbHome, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(pnThanhDonw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tab, javax.swing.GroupLayout.DEFAULT_SIZE, 1494, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnChinhLayout.setVerticalGroup(
            pnChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnChinhLayout.createSequentialGroup()
                .addGroup(pnChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tab, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnThanhDonw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnChinhLayout.createSequentialGroup()
                        .addComponent(lbHome, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnChucNang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        mnuBar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        mnuBar.setMaximumSize(new java.awt.Dimension(1, 32769));
        mnuBar.setPreferredSize(new java.awt.Dimension(1143, 100));

        mnuTaiKhoan.setText("Tài khoản");
        mnuTaiKhoan.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        mnuTaiKhoan.setMaximumSize(new java.awt.Dimension(303, 30000));

        mnuDangXuat.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        mnuDangXuat.setText("Đăng xuất");
        mnuTaiKhoan.add(mnuDangXuat);

        mnuDoiMatKhau.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        mnuDoiMatKhau.setText("Đổi mật khẩu");
        mnuDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDoiMatKhauActionPerformed(evt);
            }
        });
        mnuTaiKhoan.add(mnuDoiMatKhau);

        mnuBar.add(mnuTaiKhoan);

        mnuQLChinh.setText("Quản lí chính");
        mnuQLChinh.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N

        jMenuItem1.setText("Sản phẩm");
        mnuQLChinh.add(jMenuItem1);

        jMenuItem2.setText("Tài khoản");
        mnuQLChinh.add(jMenuItem2);

        mnuBar.add(mnuQLChinh);

        mnuQLNhanVien.setText("Quản lí nhân viên");
        mnuQLNhanVien.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        mnuBar.add(mnuQLNhanVien);

        mnuThongKe.setText("Thống kê");
        mnuThongKe.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        mnuBar.add(mnuThongKe);

        mnuCaiDat.setText("Cài đặt");
        mnuCaiDat.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        mnuBar.add(mnuCaiDat);

        setJMenuBar(mnuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnChinh, javax.swing.GroupLayout.DEFAULT_SIZE, 1811, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnChinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQLSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLSanPhamActionPerformed
        // TODO add your handling code here:
        try {
            tab.setSelectedComponent(pnl_qlSanPham.form);
        } catch (Exception e) {
            pnl_qlSanPham pnl = new pnl_qlSanPham();
            tab.add("Sản phẩm", pnl);
            tab.setSelectedComponent(pnl);
        }
    }//GEN-LAST:event_btnQLSanPhamActionPerformed

    private void btnQLNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLNhanVienActionPerformed
        // TODO add your handling code here:
        try {
            tab.setSelectedComponent(pnl_qlNhanVien.form);
        } catch (Exception e) {
            pnl_qlNhanVien pnl = new pnl_qlNhanVien();
            tab.add("Quản lí nhân viên", pnl);
            tab.setSelectedComponent(pnl);
        }
    }//GEN-LAST:event_btnQLNhanVienActionPerformed

    private void mnuDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDoiMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuDoiMatKhauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Chinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Chinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Chinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Chinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Chinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaiDat;
    private javax.swing.JButton btnDonDatHang;
    private javax.swing.JButton btnQLNhanVien;
    private javax.swing.JButton btnQLSanPham;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel lbHome;
    private javax.swing.JMenuBar mnuBar;
    private javax.swing.JMenu mnuCaiDat;
    private javax.swing.JMenuItem mnuDangXuat;
    private javax.swing.JMenuItem mnuDoiMatKhau;
    private javax.swing.JMenu mnuQLChinh;
    private javax.swing.JMenu mnuQLNhanVien;
    private javax.swing.JMenu mnuTaiKhoan;
    private javax.swing.JMenu mnuThongKe;
    private javax.swing.JPanel pnChinh;
    private javax.swing.JPanel pnChucNang;
    private javax.swing.JPanel pnThanhDonw;
    private javax.swing.JTabbedPane tab;
    // End of variables declaration//GEN-END:variables
}
