/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import doan_oracle.DBconnection;
import doan_oracle.frm_DangNhap;
/**
 *
 * @author ADMIN
 */
public class pnl_qlSanPham extends javax.swing.JPanel {
    PreparedStatement preparedStatement = null;
    ResultSet resultset = null;
   
    public static pnl_qlSanPham form;
    /**
     * Creates new form Test
     */
    public pnl_qlSanPham() {
        initComponents();
        
      
        form = this;
        showData();
        this.txtMaSanPham.setText("Mã sản phẩm tự tạo");
        this.txtMaSanPham.setEnabled(false);
    }
    private void showData(){
        try {
            jTableDanhSachSanPham.removeAll();
            String[] arr = {"Mã sản phẩm", "Tên sản phẩm", "Giá bán", "Xuất xứ", "SL tồn", "Loại SP", "Còn hàng", "Hiển thị", "Bán chạy", "SL xem"};
            DefaultTableModel model = new DefaultTableModel(arr, 0);
            
            Connection connection = DBconnection.getConnection(frm_DangNhap.tenDangNhap(), frm_DangNhap.matKhauDangNhap());
            
            String query = "SELECT * FROM dbo.[tbl_SanPham]";
            PreparedStatement ps = connection.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Vector vector = new Vector();
                vector.add(rs.getString("PK_iSanPhamID"));
                vector.add(rs.getString("sTenSanPham"));
                vector.add(rs.getString("fGiaBan"));
                vector.add(rs.getString("sXuatXu"));
                vector.add(rs.getInt("iSoLuongTon"));
                vector.add(rs.getString("FK_sDanhMucSanPhamID"));
                vector.add(rs.getBoolean("bConHang"));
                vector.add(rs.getBoolean("bHienThi"));
                vector.add(rs.getBoolean("bBanChay"));
                vector.add(rs.getInt("iSoLuongXem"));
                
                model.addRow(vector);
                
            }
            jTableDanhSachSanPham.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(jframl_qlSanPham.class.getName()).log(Level.SEVERE, null, ex);
        }
        //Load dữ liệu vào combobox
        try {
            ComboBoxLoaiSanPham.removeAll();
            String query = "SELECT sTenNhomSanPham FROM tbl_NhomSanPham";
            Connection connection = DBconnection.getConnection();
            preparedStatement = connection.prepareStatement(query);
            resultset = preparedStatement.executeQuery();            
            while(resultset.next()){
                
                cbxNhomSanPham.addItem(resultset.getString("sTenNhomSanPham"));
                
            }
            resultset.close();
            preparedStatement.close();
            connection.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
       
    }
    void lamMoiTextFiled(){
        txtMaSanPham.setText("");
        txtTenSanPham.setText("");
        txtGiaBan.setText("");
        txtSoLuongCon.setText("");
        txtSoLuongXem.setText("");
        txtXuatXu.setText("");
        txtMoTa.setText("");
        jRadioButtonOFFBanChay.setSelected(false);
        jRadioButtonONBanChay.setSelected(false);
        jRadioButtonOFFHienThi.setSelected(false);
        RadioButtonOnHienThi.setSelected(false);
        jRadioButtonONConHang.setSelected(false);
        jRadioButtonOFFConHang.setSelected(false);
        cbxNhomSanPham.insertItemAt("Chọn", 0);
        ComboBoxLoaiSanPham.insertItemAt("Chọn", 0);
        this.btnXoa.setEnabled(false);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jPanelTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jPanelSlide = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaSanPham = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTenSanPham = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtGiaBan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtXuatXu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSoLuongCon = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ComboBoxLoaiSanPham = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        RadioButtonOnHienThi = new javax.swing.JRadioButton();
        jRadioButtonOFFHienThi = new javax.swing.JRadioButton();
        jRadioButtonONConHang = new javax.swing.JRadioButton();
        jRadioButtonOFFConHang = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jRadioButtonONBanChay = new javax.swing.JRadioButton();
        jRadioButtonOFFBanChay = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        txtSoLuongXem = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtMoTa = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cbxNhomSanPham = new javax.swing.JComboBox<>();
        btnLamMoi = new javax.swing.JButton();
        jPanelDanhSachSanPham = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDanhSachSanPham1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDanhSachSanPham = new javax.swing.JTable();

        jPanelMain.setBackground(new java.awt.Color(51, 255, 102));

        jPanelTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelTitle.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelTitle.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        lblTitle.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 0, 0));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Quản Lí Sản Phẩm");

        javax.swing.GroupLayout jPanelTitleLayout = new javax.swing.GroupLayout(jPanelTitle);
        jPanelTitle.setLayout(jPanelTitleLayout);
        jPanelTitleLayout.setHorizontalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitleLayout.createSequentialGroup()
                .addGap(434, 434, 434)
                .addComponent(lblTitle)
                .addContainerGap(627, Short.MAX_VALUE))
        );
        jPanelTitleLayout.setVerticalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelSlide.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Chi tiết sản phẩm");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Mã sản phẩm: ");

        jLabel3.setText("Tên sản phẩm: ");

        txtTenSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenSanPhamActionPerformed(evt);
            }
        });

        jLabel4.setText("Giá bán");

        txtGiaBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaBanActionPerformed(evt);
            }
        });
        txtGiaBan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGiaBanKeyReleased(evt);
            }
        });

        jLabel5.setText("Xuất xứ: ");

        jLabel6.setText("Số lượng còn: ");

        txtSoLuongCon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSoLuongConKeyReleased(evt);
            }
        });

        jLabel7.setText("Loại sản phẩm: ");

        ComboBoxLoaiSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxLoaiSanPhamActionPerformed(evt);
            }
        });

        jLabel8.setText("Còn hàng: ");

        jLabel9.setText("Hiển thị: ");

        RadioButtonOnHienThi.setText("ON");

        jRadioButtonOFFHienThi.setText("OFF");

        jRadioButtonONConHang.setText("ON");

        jRadioButtonOFFConHang.setText("OFF");

        jLabel10.setText("Bán chạy: ");

        jRadioButtonONBanChay.setText("ON");

        jRadioButtonOFFBanChay.setText("OFF");

        jLabel11.setText("Số lượng xem: ");

        txtSoLuongXem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSoLuongXemKeyReleased(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(255, 255, 255));
        btnThem.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(255, 255, 255));
        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(255, 255, 255));
        btnSua.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        jLabel13.setText("Mô tả: ");

        jLabel14.setText("Hình ảnh: ");

        cbxNhomSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbxNhomSanPhamMouseClicked(evt);
            }
        });
        cbxNhomSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNhomSanPhamActionPerformed(evt);
            }
        });

        btnLamMoi.setBackground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLamMoi)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMaSanPham)
                                    .addComponent(txtGiaBan)
                                    .addComponent(txtSoLuongCon, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonONConHang)
                                    .addComponent(jRadioButtonONBanChay))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonOFFBanChay)
                                    .addComponent(jRadioButtonOFFConHang))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel11))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(RadioButtonOnHienThi)
                                .addGap(29, 29, 29)
                                .addComponent(jRadioButtonOFFHienThi))
                            .addComponent(txtTenSanPham)
                            .addComponent(txtXuatXu)
                            .addComponent(txtSoLuongXem)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(cbxNhomSanPham, 0, 99, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(ComboBoxLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(72, 72, 72))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtXuatXu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSoLuongCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(ComboBoxLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxNhomSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel13))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel14)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jRadioButtonONConHang)
                        .addComponent(jRadioButtonOFFConHang))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RadioButtonOnHienThi)
                        .addComponent(jRadioButtonOFFHienThi)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel10)
                        .addComponent(jRadioButtonONBanChay))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonOFFBanChay)
                        .addComponent(jLabel11))
                    .addComponent(txtSoLuongXem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelDanhSachSanPham.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setText("Tìm kiếm sản phẩm: ");

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        jTableDanhSachSanPham1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableDanhSachSanPham1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Giá bán", "Xuất xứ", "SL tồn", "Loại sản phẩm", "Còn hàng", "Hiển thị", "Bán chạy", "SL xem"
            }
        ));
        jScrollPane2.setViewportView(jTableDanhSachSanPham1);

        javax.swing.GroupLayout jPanelDanhSachSanPhamLayout = new javax.swing.GroupLayout(jPanelDanhSachSanPham);
        jPanelDanhSachSanPham.setLayout(jPanelDanhSachSanPhamLayout);
        jPanelDanhSachSanPhamLayout.setHorizontalGroup(
            jPanelDanhSachSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDanhSachSanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDanhSachSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDanhSachSanPhamLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTimKiem)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanelDanhSachSanPhamLayout.setVerticalGroup(
            jPanelDanhSachSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDanhSachSanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDanhSachSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        jTableDanhSachSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Giá bán", "Xuất xứ", "SL tồn", "Loại sản phẩm", "Còn hàng", "Hiển thị", "Bán chạy", "SL xem"
            }
        ));
        jTableDanhSachSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDanhSachSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDanhSachSanPham);

        javax.swing.GroupLayout jPanelSlideLayout = new javax.swing.GroupLayout(jPanelSlide);
        jPanelSlide.setLayout(jPanelSlideLayout);
        jPanelSlideLayout.setHorizontalGroup(
            jPanelSlideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSlideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanelSlideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDanhSachSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelSlideLayout.setVerticalGroup(
            jPanelSlideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSlideLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSlideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelSlideLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelDanhSachSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(jPanelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanelSlide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addComponent(jPanelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelSlide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenSanPhamActionPerformed

    private void ComboBoxLoaiSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxLoaiSanPhamActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ComboBoxLoaiSanPhamActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        try {
            //        // TODO add your handling code here:
            if(txtMaSanPham.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Mã sản phẩm không được rỗng");
                txtMaSanPham.requestFocus();
                return;
            }
            else if(txtTenSanPham.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Tên sản phẩm không được rỗng");
                txtTenSanPham.requestFocus();
                return;
            }
            
            else if (txtGiaBan.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Giá bán hông được rỗng");
                txtGiaBan.requestFocus();
                return;
            }
            else if (txtXuatXu.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Sản phẩm xuất xứ ở đâu");
                txtXuatXu.requestFocus();
                return;
            }
            else if (txtSoLuongCon.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Tên sản phẩm hông được rỗng");
                txtSoLuongCon.requestFocus();
                return;
            }
//            else if (ComboBoxLoaiSanPham.getSelectedItem().equals("")) {
//                JOptionPane.showMessageDialog(null, "Tên sản phẩm hông được rỗng");
//                return;
//            }
            else if (txtSoLuongXem.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Tên sản phẩm hông được rỗng");
                txtSoLuongXem.requestFocus();
                return;
            }
            Connection con = DBconnection.getConnection(frm_DangNhap.tenDangNhap(), frm_DangNhap.matKhauDangNhap());
            
            String query = "INSERT INTO tbl_SanPham"
                    + "(FK_sDanhMucSanPhamID, sTenSanPham, sMoTa, sXuatXu, fGiaBan, iSoLuongTon, iSoLuongXem, bConHang, bBanChay, bHienThi, FK_iGiamGiaID, FK_iKhoHangID)"
                    + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            preparedStatement = con.prepareStatement(query);
            preparedStatement.setString(1, "Iphone"); //Phải lấy dữ liệu từ dropdownlist
            preparedStatement.setString(2, txtTenSanPham.getText());
            preparedStatement.setString(3, txtMoTa.getText());
            preparedStatement.setString(4, txtXuatXu.getText());
            preparedStatement.setString(5, txtGiaBan.getText());
            preparedStatement.setString(6, txtSoLuongCon.getText());
            preparedStatement.setString(7, txtSoLuongXem.getText());
            //Giảm giá và kho hàng ĐẶT MẶT ĐỊNH LÀ 1 nằm ở vị trí thứ 11 và 12
            preparedStatement.setString(11, "1");
            preparedStatement.setString(12, "1");
            
            if(jRadioButtonONConHang.getText().equals("ON"))
                preparedStatement.setString(8, "True");
//            else (jRadioButtonOFFConHang.getText().equals("OFF"))
            else
                preparedStatement.setString(8, "False");
            if(jRadioButtonONBanChay.getText().equals("ON"))
                preparedStatement.setString(9, "True");
//            else if(jRadioButtonOFFBanChay.getText().equals("OFF"))
            else
                preparedStatement.setString(9, "False");
            if(jRadioButtonOFFHienThi.getText().equals("OFF"))
                preparedStatement.setString(10, "False");
            else 
                preparedStatement.setString(10, "True");
            preparedStatement.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(pnl_qlSanPham.class.getName()).log(Level.SEVERE, null, ex);
        }
        showData();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
//        TimKiem tk = new TimKiem(this, true);
//        tk.setVisible(true);
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void cbxNhomSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNhomSanPhamActionPerformed
        // TODO add your handling code here:
//         try {
//            ComboBoxLoaiSanPham.removeAll();
//            String query = "SELECT PK_sDanhMucSanPhamID FROM tbl_DanhMucSanPham WHERE FK_sNhomSanPhamID = (SELECT PK_sNhomSanPhamID FROM tbl_NhomSanPham WHERE sTenNhomSanPham = '"+cbxNhomSanPham.getSelectedItem()+"')";
//            Connection connection = DBconnection.getConnection();
//            preparedStatement = connection.prepareStatement(query);
//            resultset = preparedStatement.executeQuery();
//            while (resultset.next()){
//                ComboBoxLoaiSanPham.addItem(resultset.getString("PK_sDanhMucSanPham"));
//            }
//           // resultset.close();
//           // preparedStatement.close();
//            //connection.close();
//         } catch (Exception e) {
//             JOptionPane.showMessageDialog(this, e.getMessage());
//             e.printStackTrace();
//        }
    }//GEN-LAST:event_cbxNhomSanPhamActionPerformed

    private void cbxNhomSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxNhomSanPhamMouseClicked
        // TODO add your handling code here:
//        try {
//            ComboBoxLoaiSanPham.removeAll();
//            String selectItems = (String)cbxNhomSanPham.getSelectedItem();
//          //  String query = "SELECT PK_sDanhMucSanPhamID FROM tbl_DanhMucSanPham WHERE FK_sNhomSanPhamID = (SELECT PK_sNhomSanPhamID FROM tbl_NhomSanPham WHERE sTenNhomSanPham = N'"+cbxNhomSanPham.getSelectedItem()+"')";
//            String query = "SELECT PK_sDanhMucSanPhamID FROM tbl_DanhMucSanPham WHERE FK_sNhomSanPhamID = (SELECT PK_sNhomSanPhamID FROM tbl_NhomSanPham WHERE sTenNhomSanPham = N'"+selectItems+"')";
//         
//            //SELECT PK_sDanhMucSanPhamID FROM tbl_DanhMucSanPham WHERE FK_sNhomSanPhamID = (SELECT PK_sNhomSanPhamID FROM tbl_NhomSanPham WHERE sTenNhomSanPham = N'Điện thoại')
//            Connection connection = DBconnection.getConnection();
//            preparedStatement = connection.prepareStatement(query);
//            resultset = preparedStatement.executeQuery();
//            while (resultset.next()){
//                ComboBoxLoaiSanPham.addItem(resultset.getString("PK_sDanhMucSanPham"));
//            }
//           // resultset.close();
//           // preparedStatement.close();
//            //connection.close();
//         } catch (Exception e) {
//             JOptionPane.showMessageDialog(this, e.getMessage());
//             e.printStackTrace();
//        }
    }//GEN-LAST:event_cbxNhomSanPhamMouseClicked

    private void jTableDanhSachSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDanhSachSanPhamMouseClicked
       
            // TODO add your handling code here:
            int i = jTableDanhSachSanPham.getSelectedRow();
//
            TableModel model = jTableDanhSachSanPham.getModel();

        txtMaSanPham.setText(model.getValueAt(i, 0).toString());
        txtTenSanPham.setText(model.getValueAt(i, 1).toString());
        txtGiaBan.setText(model.getValueAt(i, 2).toString());
        txtXuatXu.setText(model.getValueAt(i, 3).toString());
        txtSoLuongCon.setText(model.getValueAt(i, 4).toString());

        String conHang = model.getValueAt(i, 6).toString();
            switch(conHang){
                case "true":
                    jRadioButtonONConHang.setSelected(true);
                    jRadioButtonOFFBanChay.setSelected(false);
                    break;
                default:
                    jRadioButtonONConHang.setSelected(false);
                    jRadioButtonOFFBanChay.setSelected(true);
                    break;
            }
        String hienThi = model.getValueAt(i, 7).toString();
            switch(hienThi){
                case "true":
                    jRadioButtonOFFHienThi.setSelected(false);
                    RadioButtonOnHienThi.setSelected(true);
                    break;
                default:
                    jRadioButtonOFFHienThi.setSelected(true);
                    RadioButtonOnHienThi.setSelected(false);
                    break;
            }
        String banChay = model.getValueAt(i, 8).toString();
            switch(banChay){
                case "true":
                    jRadioButtonONBanChay.setSelected(true);
                    jRadioButtonOFFConHang.setSelected(false);
                    break;
                default:
                    jRadioButtonONBanChay.setSelected(false);
                    jRadioButtonOFFConHang.setSelected(true);
                    break;
            }
        txtSoLuongXem.setText(model.getValueAt(i, 9).toString());
        
        this.btnThem.setEnabled(false);
        this.btnXoa.setEnabled(true);
          
        
    }//GEN-LAST:event_jTableDanhSachSanPhamMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        try {
            String query = "DELETE FROM tbl_SanPham WHERE PK_iSanPhamID = ?";
            Connection connection = DBconnection.getConnection(frm_DangNhap.tenDangNhap(), frm_DangNhap.matKhauDangNhap());
            preparedStatement = connection.prepareStatement(query);
           if(txtMaSanPham.getText().equals("")){
               JOptionPane.showMessageDialog(this, "Chọn hoặc nhập mã sản phẩm để xóa");
           }
           else {
            preparedStatement.setString(1, txtMaSanPham.getText());
            preparedStatement.executeUpdate();
            JOptionPane.showMessageDialog(this, "Xóa thành công");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        lamMoiTextFiled();
        showData();
        this.btnThem.setEnabled(true);
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        try {            
            if(txtMaSanPham.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Mã sản phẩm không được rỗng");
                txtMaSanPham.requestFocus();
                return;
            }
            else if(txtTenSanPham.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Tên sản phẩm không được rỗng");
                txtTenSanPham.requestFocus();
                return;
            }
            
            else if (txtGiaBan.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Giá bán hông được rỗng");
                txtGiaBan.requestFocus();
                return;
            }
            else if (txtXuatXu.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Sản phẩm xuất xứ ở đâu");
                txtXuatXu.requestFocus();
                return;
            }
            else if (txtSoLuongCon.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Tên sản phẩm hông được rỗng");
                txtSoLuongCon.requestFocus();
                return;
            }
//            else if (ComboBoxLoaiSanPham.getSelectedItem().equals("")) {
//                JOptionPane.showMessageDialog(null, "Tên sản phẩm hông được rỗng");
//                return;
//            }
            else if (txtSoLuongXem.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Tên sản phẩm hông được rỗng");
                txtSoLuongXem.requestFocus();
                return;
            }
            Connection con = DBconnection.getConnection(frm_DangNhap.tenDangNhap(), frm_DangNhap.matKhauDangNhap());
            
//            String query1 = "UPDATE tbl_SanPham"
//                    + "(FK_sDanhMucSanPhamID, sTenSanPham, sMoTa, sXuatXu, fGiaBan, iSoLuongTon, iSoLuongXem, bConHang, bBanChay, bHienThi, FK_iGiamGiaID, FK_iKhoHangID)"
//                    + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            String query = "UPDATE tbl_SanPham"
                        + " SET FK_sDanhMucSanPhamID=?, sTenSanPham=?, sMoTa=?, sXuatXu=?, fGiaBan=?, iSoLuongTon=?, iSoLuongXem=?, bConHang=?, bBanChay=?, bHienThi=?, FK_iGiamGiaID=?, FK_iKhoHangID=?"
                        + " WHERE PK_iSanPhamID=?";
            preparedStatement = con.prepareStatement(query);
            preparedStatement.setString(13, txtMaSanPham.getText());
            preparedStatement.setString(1, "Iphone"); //Phải lấy dữ liệu từ dropdownlist
            preparedStatement.setString(2, txtTenSanPham.getText());
            preparedStatement.setString(3, txtMoTa.getText());
            preparedStatement.setString(4, txtXuatXu.getText());
            preparedStatement.setString(5, txtGiaBan.getText());
            preparedStatement.setString(6, txtSoLuongCon.getText());
            preparedStatement.setString(7, txtSoLuongXem.getText());
            //Giảm giá và kho hàng ĐẶT MẶT ĐỊNH LÀ 1 nằm ở vị trí thứ 11 và 12
            preparedStatement.setString(11, "1");
            preparedStatement.setString(12, "1");
                
            if(jRadioButtonONConHang.getText().equals("ON"))
                preparedStatement.setString(8, "True");
//            else (jRadioButtonOFFConHang.getText().equals("OFF"))
            else
                preparedStatement.setString(8, "False");
            if(jRadioButtonONBanChay.getText().equals("ON"))
                preparedStatement.setString(9, "True");
//            else if(jRadioButtonOFFBanChay.getText().equals("OFF"))
            else
                preparedStatement.setString(9, "False");
            if(jRadioButtonOFFHienThi.getText().equals("OFF"))
                preparedStatement.setString(10, "False");
            else 
                preparedStatement.setString(10, "True");
            preparedStatement.executeUpdate();
            JOptionPane.showMessageDialog(null, "Cập nhật thành công");
        } catch (SQLException ex) {
            Logger.getLogger(pnl_qlSanPham.class.getName()).log(Level.SEVERE, null, ex);
        }
        showData();
        
    }//GEN-LAST:event_btnSuaActionPerformed

    private void txtSoLuongConKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoLuongConKeyReleased
        // TODO add your handling code here:
        try {
            double so = ChuyenDoi.ChuyenSangSo(txtSoLuongCon.getText());
            String soLuong = ChuyenDoi.DinhDangSo(so);
            txtSoLuongCon.setText(soLuong);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtSoLuongConKeyReleased

    private void txtSoLuongXemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoLuongXemKeyReleased
        // TODO add your handling code here:
//        try {
//            double so = ChuyenDoi.ChuyenSangSo(txtSoLuongXem.getText());
//            String soLuong = ChuyenDoi.DinhDangSo(so);
//            txtSoLuongXem.setText(soLuong);
//        } catch (Exception e) {
//        }
    }//GEN-LAST:event_txtSoLuongXemKeyReleased

    private void txtGiaBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaBanActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtGiaBanActionPerformed

    private void txtGiaBanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiaBanKeyReleased
        // TODO add your handling code here:
//        try {
//            double so = ChuyenDoi.ChuyenSangSo(txtGiaBan.getText());
//            String giaBan = ChuyenDoi.DinhDangSo(so);
//            txtGiaBan.setText(giaBan);
//        } catch (Exception e) {
//        }
    }//GEN-LAST:event_txtGiaBanKeyReleased

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        lamMoiTextFiled();
        this.btnThem.setEnabled(true);
        this.txtMaSanPham.setText("Mã sản phẩm được tự tạo");
        this.txtMaSanPham.setEnabled(false);
    }//GEN-LAST:event_btnLamMoiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxLoaiSanPham;
    private javax.swing.JRadioButton RadioButtonOnHienThi;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbxNhomSanPham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelDanhSachSanPham;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelSlide;
    private javax.swing.JPanel jPanelTitle;
    private javax.swing.JRadioButton jRadioButtonOFFBanChay;
    private javax.swing.JRadioButton jRadioButtonOFFConHang;
    private javax.swing.JRadioButton jRadioButtonOFFHienThi;
    private javax.swing.JRadioButton jRadioButtonONBanChay;
    private javax.swing.JRadioButton jRadioButtonONConHang;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableDanhSachSanPham;
    private javax.swing.JTable jTableDanhSachSanPham1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtMaSanPham;
    private javax.swing.JTextField txtMoTa;
    private javax.swing.JTextField txtSoLuongCon;
    private javax.swing.JTextField txtSoLuongXem;
    private javax.swing.JTextField txtTenSanPham;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtXuatXu;
    // End of variables declaration//GEN-END:variables
}
